"""
Django settings for test1 project.

Generated by 'django-admin startproject' using Django 1.8.

For more information on this file, see
https://docs.djangoproject.com/en/dev/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/dev/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
#coding=utf-8
import os
#from django.conf.global_settings import MEDIA_ROOT
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

#TEMPLATE_DIRS = (os.path.join(BASE_DIR, 'templates'),)
#TEMPLATE_DIRS = ('/root/workspace/test1/templates',)

#MEDIA_ROOT = "/tmp/"
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/dev/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = ')rd2@$g(lc+p)e7i^xa#*^37z--@+=42otoq)65eul8u3n7@5w'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

TEMPLATE_DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1','localhost']



LOGIN_URL = '/app-info/'

# Application definition

INSTALLED_APPS = (
    'django_crontab',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'app',
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
#    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
#    'django.middleware.security.SecurityMiddleware',
)

ROOT_URLCONF = 'workflow.urls'
WSGI_APPLICATION = 'workflow.wsgi.application'

#ESSION_SAVE_EVERY_REQUEST = True
SESSION_COOKIE_AGE = 60*30
SESSION_EXPIRE_AT_BROWSER_CLOSE = True



##TEMPLATES
TEMPLATE_CONTEXT_PROCESSORS = (
    "django.contrib.auth.context_processors.auth",
    "django.core.context_processors.debug",
    "django.core.context_processors.i18n",
    "django.core.context_processors.media",
    "django.core.context_processors.static",
    "django.core.context_processors.tz",
    "django.contrib.messages.context_processors.messages",
#    "blog.commons.context_processors.custom_proc",
    "django.core.context_processors.request",
)




TEMPLATE_DIRS = (
    os.path.join(BASE_DIR, 'templates'),
)


#TEMPLATES = [
#    {
#        'BACKEND': 'django.template.backends.django.DjangoTemplates',
#        'DIRS': [os.path.join(BASE_DIR, 'templates'),],
##        'APP_DIRS': True,
#       'OPTIONS': {
#            'context_processors': [
#                'django.template.context_processors.debug',
#                'django.template.context_processors.request',
#                'django.contrib.auth.context_processors.auth',
#                'django.contrib.messages.context_processors.messages',
#            ],
#        },
#    },
#]


#WSGI_APPLICATION = 'test1.wsgi.application'


# Database
# https://docs.djangoproject.com/en/dev/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'workflow1',
        'USER': 'root',
    }
}


# Internationalization
# https://docs.djangoproject.com/en/dev/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/dev/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'static'),
#    '/var/www/static/',
)

DEFAULT_CHARSET = 'utf-8'

#MEDIA_ROOT = (os.path.join(BASE_DIR, "media"),)
MEDIA_ROOT = "/media/"
MEDIA_URL = "/media/"

FILE_UPLOAD_HANDLERS = (
                        "django.core.files.uploadhandler.MemoryFileUploadHandler",
                        "django.core.files.uploadhandler.TemporaryFileUploadHandler",
                        )





AUTHENTICATION_BACKENDS = (
                           "django_auth_ldap.backend.LDAPBackend",
                           "django.contrib.auth.backends.ModelBackend",
                           )


DJANGO_LOG_LEVEL=DEBUG


#CRONTAB
CRONJOBS = [
('*/5 * * * *', 'app.views.create_mail', '>> /tmp/eters.log'),
('*/30 * * * *', 'app.views.confirm_mail', '>> /tmp/eters.log')
]

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'file': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': '/path/to/django/debug.log',
        },
    },
    'loggers': {
        'django.request': {
            'handlers': ['file'],
            'level': 'DEBUG',
            'propagate': True,
        },
    },
}
